os:
  - linux
#  - windows

#  - osx

arch: arm64

dist: bionic

sudo: required

language: python


python:
  - "3.8"
#  - "3.8-dev"  # 3.8 development branch
#  - "nightly"  # nightly build

before_install:
  - python3.8 -m venv ~/ENV3
  - source ~/ENV3/bin/activate
  - pip install pip -U

install:
  - pip --version
  - which pip
  - pwd
  - python --version
  - which python
  - pip user install -r requirements.txt
  - pip install -r requirements-dev.txt
  - pip install .
  - ls
  - pwd

script: pytest -v --capture=no tests/test_installer.py
