os:
  - linux
#  - windows

#  - osx

arch: arm64

dist: bionic

sudo: required

language: python


python:
  - "3.8"
#  - "3.8-dev"  # 3.8 development branch
#  - "nightly"  # nightly build

install:
  - python3.8 -m venv ~/ENV3
  - source ~/ENV3/bin/activate
  - pip install --user pip -U
  - pwd
  - pip --version
  - python --version
#  - pip install -r requirements-dev.txt
  - pip install .
  - ls
  - pwd
  - python --version

script: pytest -v --capture=no tests/test_installer.py
