os:
  - linux

arch: arm64

sudo: required

python:
  - "3.8.2"

cache: false

dist: bionic

language: python

before_install:
  - sudo apt-get install build-essential libssl-dev libffi-dev
  - sudo apt-get install python3-tk
  - python --version
  - python -m venv ~/ENV3
  - source ~/ENV3/bin/activate
  - pip install pip -U
  - pip --version
  - which python
  - which pip
  - pwd

install:
#  - sudo pip install cryptography --no-binary cryptography
  - pip install -r requirements.txt
#  - pip install -r requirements-dev.txt
  - pip install pytest
  - pip install .

script:
  - pip install cloudmesh-configuration
  - pytest -v --capture=no tests/test_installer.py
