os:
  - linux
#  - windows

#  - osx

arch: arm64

dist: bionic

sudo: required

language: python


python:
  - "3.8.2"

before_install:
  - pip3.8 install --upgrade pip
  - python3.8 -m venv ~/ENV3
  - source ~/ENV3/bin/activate

install:
  - pwd
  - ~/ENV3/bin/pip --version
  - python --version
  - which python
  - ~/ENV3/bin/pip install pytest
  - ~/ENV3/bin/pip install -r requirements.txt
  - ~/ENV3/bin/pip install .
  - ls
  - pwd

script:
  - ~/ENV3/bin/pip install cloudmesh-configuration
  - pytest -v --capture=no tests/test_installer.py
